-- 1 List the number of films per category.
SELECT c.name, count(distinct film_id) 
FROM film_category fc
INNER JOIN category c
ON fc.category_id=c.category_id
GROUP BY c.name;
-- 2 Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country
FROM store s
INNER JOIN address a
ON s.address_id=a.address_id
INNER JOIN city c
ON a.city_id=c.city_id
INNER JOIN country co
ON co.country_id=c.country_id;
-- 3 Calculate the total revenue generated by each store in dollars.
SELECT c.store_id, SUM(p.amount)
FROM customer c
JOIN payment p
ON c.customer_id=p.customer_id
GROUP BY c.store_id;
-- 4 Determine the average running time of films for each category.
SELECT ca.name, AVG(length) AS avg_length
FROM category ca
JOIN film_category fc
ON ca.category_id=fc.category_id
JOIN film f
on fc.film_id=f.film_id
GROUP BY ca.name;
-- 5 Identify the film categories with the longest average running time.
SELECT ca.name, AVG(f.length) AS avg_length
FROM category ca
JOIN film_category fc
ON ca.category_id = fc.category_id
JOIN film f
ON fc.film_id = f.film_id
GROUP BY ca.name
HAVING AVG(f.length) > (
    SELECT MAX(avg_length)
    FROM (
        SELECT AVG(f.length) AS avg_length
        FROM film f
		JOIN film_category fc
		ON f.film_id=fc.film_id
		JOIN category c
		ON fc.category_id=c.category_id
		) AS subquery
);
-- 6 Display the top 10 most frequently rented movies in descending order.
SELECT f.title, COUNT(r.rental_date) AS count_rental
FROM film f
JOIN inventory i
ON f.film_id=i.film_id
JOIN rental r
ON r.inventory_id=i.inventory_id
GROUP BY f.title
ORDER BY count_rental DESC
LIMIT 10;
-- 7 Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT DISTINCT f.title, f.film_id, i.store_id
FROM film f
JOIN inventory i
ON i.film_id=f.film_id
WHERE lower(f.title) = 'academy dinosaur' AND i.store_id=1;
-- 8
SELECT f.title, 
CASE 
	WHEN f.title NOT IN (SELECT f.title
				FROM film f
				JOIN inventory i ON f.film_id = i.film_id) THEN 'Available'
	ELSE 'Not Available'
END AS status_avail
FROM film f;



